services:
  codecrush:
    build:
      context: .
      args:
        # Expose REACT_APP variables to the Docker build for the client-side compilation
        - REACT_APP_MICROSOFT_CLIENT_ID=${REACT_APP_MICROSOFT_CLIENT_ID}
        - REACT_APP_MICROSOFT_TENANT_ID=${REACT_APP_MICROSOFT_TENANT_ID}
    ports:
      - "443:443"
      - "80:80"
    # Use env_file to load all variables from .env into the container at runtime
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - language-servers:/app/language-servers
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Piston service if running locally
  # piston:
  #   ...

volumes:
  language-servers:

networks:
  codecrush-network:
    driver: bridge 