services:
  codecrush-blue:
    build: .
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - PORT=3001
      - PISTON_API_URL=http://host.docker.internal:2000/api/v2/execute
      - DATABASE_URL=postgresql://agale@host.docker.internal:5432/codepad
      - LSP_GATEWAY_HOST=lsp-gateway
    restart: unless-stopped
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  codecrush-green:
    build: .
    expose:
      - "3002"
    env_file:
      - .env
    environment:
      - PORT=3002
      - PISTON_API_URL=http://host.docker.internal:2000/api/v2/execute
      - DATABASE_URL=postgresql://agale@host.docker.internal:5432/codepad
      - LSP_GATEWAY_HOST=lsp-gateway
    restart: unless-stopped
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lsp-gateway:
    build:
      context: ./lsp-gateway
    restart: unless-stopped
    networks:
      - codecrush-network
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./upstream.conf:/etc/nginx/upstream.conf
    depends_on:
      - codecrush-blue
      - codecrush-green
      - lsp-gateway
    restart: unless-stopped
    networks:
      - codecrush-network


networks:
  codecrush-network:
    driver: bridge
