services:
  codecrush-blue:
    build: .
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - PORT=3001
    restart: unless-stopped
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  codecrush-green:
    build: .
    expose:
      - "3002"
    env_file:
      - .env
    environment:
      - PORT=3002
    restart: unless-stopped
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lsp-gateway:
    build:
      context: ./lsp-gateway
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - codecrush-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.blue-green.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/interview-applications-sbx.tamg.cloud/fullchain.pem:/etc/ssl/certs/server.crt:ro
      - /etc/letsencrypt/live/interview-applications-sbx.tamg.cloud/privkey.pem:/etc/ssl/private/server.key:ro
    depends_on:
      - codecrush-blue
      - codecrush-green
    restart: unless-stopped
    networks:
      - codecrush-network


networks:
  codecrush-network:
    driver: bridge 