services:
  codecrush:
    build: .
    ports:
      - "3001:3001"  # Internal port only
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_SSL=true
      - PISTON_API_URL=${PISTON_API_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # <-- FIX for RDS certificate issue
    restart: unless-stopped
    volumes:
      - language-servers:/app/language-servers
    networks:
      - codecrush-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"      # Standard HTTP port
      - "443:443"    # Standard HTTPS port (for future SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - codecrush
    restart: unless-stopped
    networks:
      - codecrush-network

volumes:
  language-servers:

networks:
  codecrush-network:
    driver: bridge 