services:
  - type: web
    name: codepad-piston
    runtime: image
    image:
      url: ghcr.io/engineer-man/piston
    plan: starter
    region: oregon
    env: production
    healthCheckPath: /api/v2/runtimes
    scaling:
      minInstances: 1
      maxInstances: 1
      targetCPUPercent: 70
    disk:
      name: piston-data
      mountPath: /piston
    envVars:
      - key: PISTON_LOG_LEVEL
        value: INFO

# The following are no longer needed as we are using the official image
# and Render's dynamic port assignment.
#    port: 2000
#    envVars:
#      - key: PISTON_LOG_LEVEL
#        value: INFO
#      - key: PISTON_BIND_ADDR
#        value: 0.0.0.0:2000
#    scaling:
#      minInstances: 1
#      maxInstances: 1
#      targetCPUPercent: 70 